// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaShop.Services;

namespace PizzaShop.Migrations
{
    [DbContext(typeof(PizzaShopContext))]
    [Migration("20190822164136_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("PizzaShop.Models.Diameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DiameterValue");

                    b.HasKey("Id");

                    b.ToTable("Diameters");

                    b.HasAnnotation("MySQL:Charset", "utf8");
                });

            modelBuilder.Entity("PizzaShop.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasAnnotation("MySQL:Charset", "utf8");
                });

            modelBuilder.Entity("PizzaShop.Models.PizzaDiameter", b =>
                {
                    b.Property<int>("DiameterId");

                    b.Property<int>("PizzaId");

                    b.HasKey("DiameterId", "PizzaId");

                    b.HasIndex("PizzaId");

                    b.ToTable("PizzaDiameters");

                    b.HasAnnotation("MySQL:Charset", "utf8");
                });

            modelBuilder.Entity("PizzaShop.Models.PizzaDiameter", b =>
                {
                    b.HasOne("PizzaShop.Models.Diameter", "Diameter")
                        .WithMany()
                        .HasForeignKey("DiameterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PizzaShop.Models.Pizza", "Pizza")
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
